### PR TITLE
feat: convert abroot to use orchid library

### PR DESCRIPTION
**Pull request by bketelsen**
If merged this PR will convert abroot to use the orchid library. No new functionality is added.

### CODE REVIEW

**Comment by bketelsen** [comment]
@mirkobrombin before merging the Version string in main.go needs to be updated. I'm going to add a ticket to get the version string automatically in the future.

**Comment by matbme** [comment]
Can we also change the `fmt.Print` and `PrintVerbose` calls inside `core`? Or do we create a separate PR for this?

**Comment by bketelsen** [comment]
> Can we also change the `fmt.Print` and `PrintVerbose` calls inside `core`? Or do we create a separate PR for this?

I posted a message about this in Discord a few days ago. My strong opinion is that `core` shouldn't be doing any output at all, it should only send errors and messages back to the cli, which should do all the output. So my preference is reworking all the `core` code to send back errors & statuses which get printed by things in the `cmd` folder.

**Comment by matbme** [comment]
>  So my preference is reworking all the core code to send back errors & statuses which get printed by things in the cmd folder.

Makes sense. So the general idea would be to have a file inside `cmd` with functions for formatting output? I.e a PrintVerbose, PrintWarning, PrintInfo, etc?

**Comment by bketelsen** [comment]
> Makes sense. So the general idea would be to have a file inside `cmd` with functions for formatting output? I.e a PrintVerbose, PrintWarning, PrintInfo, etc?

The orchid library already has all those functions, so they don't even need to be added. Instead we'd add strings to the localization file for the messages that need to be printed and print the localized responses from the command that called the library function.

**Comment by bketelsen** [comment]
> > Makes sense. So the general idea would be to have a file inside `cmd` with functions for formatting output? I.e a PrintVerbose, PrintWarning, PrintInfo, etc?
> 
> The orchid library already has all those functions, so they don't even need to be added. Instead we'd add strings to the localization file for the messages that need to be printed and print the localized responses from the command that called the library function.

for example: 
https://github.com/Vanilla-OS/ABRoot/blob/main/core/transaction.go#L44
this line prints an error from inside core. Instead we should create a named error type and return that to the calling code in the `cmd` folder, which can then use the localization built into orchid to display it to the terminal.

**Comment by mirkobrombin** [comment]
> So my preference is reworking all the core code to send back errors & statuses which get printed by things in the cmd folder.

I agree with this

**Review by mirkobrombin — APPROVED** [review]

**Pull request merged**
