### PR TITLE
cmd/pkg: Apply operation

### PR DESCRIPTION
**Pull request by matbme**
This PR adds the `abroot pkg apply` operation to apply package changes based on the current image.

This operation assumes that the base image used to build the current root is available either locally or on the remote (which we shouldn't have to pull from but are able to if necessary). This means that we need to make sure we always keep around the current image, as well as the previous root image if it isn't the same. 

Another option would be to use the image ABRoot builds when running the upgrade, but we would need to make sure that any package that was removed from `packages.add` or `packages.remove` gets removed/reinstalled.

@mirkobrombin what's your input on this? It's important to keep in mind that each image is over 4GB, so we should keep as few images as possible

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Newest images should be around 2GB now, make sure to pull the new one or reset the storage in your next test.
Personally I'm fine with using the pulled one instead of the locally built, since that could already include some changes which we can remove easily since added and removed packages are stored in different files, but at cost of big layers, since adding then removing will still add bytes to the layer

**Comment by matbme** [comment]
> Newest images should be around 2GB now

I'm pretty sure 2GB is their compressed size. They are still taking 4GB in storage on a fresh install.

image

**Comment by mirkobrombin** [comment]
makes sense

**Comment by matbme** [comment]
The new container storage logic is implemented. ABRoot should now automatically remove old images and use new build images for apply operations. @mirkobrombin could you take a look again?

**Review by mirkobrombin — APPROVED** [review]

**Pull request merged**
