### PR TITLE
Mount a custom home partition

### PR DESCRIPTION
**Pull request by muhdsalm**
This is kinda part one in the process to support custom home partitions. This a sort of roadmap of the process:

- [x] Implement mounting custom home partitions
- [ ] Implement decrypting encrypted home partitions 
Up till this point, to add a custom home partition you have to mess around with `abroot.json` and filesystem labels yourself.
- [x] Implement adding a custom home partition in the [Vanilla Installer](https://github.com/Vanilla-OS/vanilla-installer)
- [ ] Implement encrypting the home partition in the installer
- [ ] Implement adding an encrypted home partition in the installer. This could also extend to adding an encrypted var partition as well

### CODE REVIEW

**Comment by muhdsalm** [comment]
I really have no idea if the decryption thing works or not because I don't have any encrypted on my system. If someone does, please do let me know if it works.

**Comment by muhdsalm** [comment]
Update: works on my machine (also I finally don't have to mount my home partition by hand anymore 😁)

You can test it by using the `muhdsalm/test` image

**Review by taukakao — CHANGES_REQUESTED** [review]
Sorry, but I think this is quite unnecessary.
In my opinion, we should just make home a symlink to /var/home.
It's how Silverblue does it and would allow mounting something in /home (would mount to /var/home)

Also, /home doesn't need to exist before systemd so I strongly disagree with putting all the logic here.

**Comment by mirkobrombin** [comment]
That's also fair

**Comment by muhdsalm** [comment]
Maybe it's just me, but the fact that `/var/home` is bind mounted to `/home` means that a lot of configuration doesn't break if I were to install a different distro and it's expecting `/var/home` (which doesn't exist anymore). And keeping configuration between different systems is one of the reasons to use a custom home partition.

**Comment by muhdsalm** [comment]
> @muhdsalm Could you elaborate? I don't understand what you mean.
> 
> If you were to switch from a different OS with a separate home partition to an ABRoot based OS you could just put the mount to /home in your fstab and systemd would automatically mount it in /var/home
> Currently it's not possible since systemd doesn't overwrite the mount in /home but if it's a symlink it should work.

Some application configs break when switching from a system with $HOME set as `/var/home` to system with $HOME set to `/home` because they expect `/var/home` to still be there on the new system.

**Comment by taukakao** [comment]
With a symlink, we would still use /home for $HOME
Using a bind mount or a symlink should behave almost identically.

**Comment by muhdsalm** [comment]
> With a symlink, we would still use /home for $HOME
> Using a bind mount or a symlink should behave almost identically. 

Oh ok, cool

**Comment by muhdsalm** [comment]
> I'm really sorry, I see that work went into this, I just think it's way too overkill for what we're trying to do here.
> 
> In my opinion, we should just make /home a symlink to /var/home. It's how Silverblue does it and would allow mounting something in /home (would mount to /var/home)
> 
> Also, /home doesn't need to exist before systemd so I strongly disagree with putting all the logic here.

Would the decryption be a reason to put the logic here?

**Comment by taukakao** [comment]
@muhdsalm 
No, decryption should be handled like in other distros through fstab and crypttab in my opinion.

The only reason why we need /var this early is because it contains part of /etc

**Review by taukakao — CHANGES_REQUESTED** [review]
Seems to me like there's no checking if the symlink exists already. 
If I'm wrong and you tested this across an update and multiple reboots then you can resolve this.

**Comment by muhdsalm** [comment]
Perhaps encryption should be handled in a different PR

**Comment by taukakao** [comment]
I'm closing this since I'm against handling home as some special folder here.

With #380 users can just mount /home from their /etc/fstab.

**Pull request closed without merging**
