### PR TITLE
Draft: Replace custom merge function with EtcBuilder

### PR DESCRIPTION
**Pull request by axtloss**
Instead of using a custom merge function, abroot will use EtcBuilder from linux-immutability-tools to handle multiple etc directories properly.

This will require changes in the vanilla os base image.
I have also not tested these changes yet.

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Didn’t tested it yet but the implementation looks good.

**Comment by axtloss** [comment]
This unveiled an issue in the installer that caused it to modify the system etc, causing EtcBuilder not to work. I am not sure if that issue has been fixed yet, but I wasn't able to test if it works.

**Comment by mirkobrombin** [comment]
setting up a vm to test this and #72 (I don't think I have the time this evening, for sure this weekend)

**Comment by axtloss** [comment]
This pr is so old its easier to just open a new one based on the latest changes.

**Pull request closed without merging**
